### ISSUE TITLE
lib/relaton_iho/xml_parser.rb:46:in `iho_group': undefined method `text' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by CAMOBAP** [relaton/relaton-iho#11]
https://github.com/metanorma/mn-samples-iho/runs/2038840416?check_suite_focus=true#step:5:41440

Can be reproduced with `metanorma site generate . -o published -c metanorma.yml --agree-to-terms` command

```
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-iho-1.7.0/lib/relaton_iho/xml_parser.rb:46:in `iho_group': undefined method `text' for nil:NilClass (NoMethodError)
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-iho-1.7.0/lib/relaton_iho/xml_parser.rb:31:in `block (2 levels) in fetch_editorialgroup'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:238:in `block in each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `upto'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-iho-1.7.0/lib/relaton_iho/xml_parser.rb:30:in `map'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-iho-1.7.0/lib/relaton_iho/xml_parser.rb:30:in `block in fetch_editorialgroup'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:238:in `block in each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `upto'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-iho-1.7.0/lib/relaton_iho/xml_parser.rb:29:in `map'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-iho-1.7.0/lib/relaton_iho/xml_parser.rb:29:in `fetch_editorialgroup'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-bib-1.7.1/lib/relaton_bib/xml_parser.rb:55:in `item_data'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-iho-1.7.0/lib/relaton_iho/xml_parser.rb:10:in `item_data'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-bib-1.7.1/lib/relaton_bib/xml_parser.rb:11:in `from_xml'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-iho-1.7.0/lib/relaton_iho/processor.rb:25:in `from_xml'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-cli-1.7.0/lib/relaton/cli.rb:40:in `parse_xml'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-cli-1.7.0/lib/relaton/bibdata.rb:41:in `from_xml'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-cli-1.7.0/lib/relaton/cli/relaton_file.rb:196:in `bibdata_instance'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-cli-1.7.0/lib/relaton/cli/relaton_file.rb:150:in `block in concatenate_files'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-cli-1.7.0/lib/relaton/cli/relaton_file.rb:142:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-cli-1.7.0/lib/relaton/cli/relaton_file.rb:142:in `reduce'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-cli-1.7.0/lib/relaton/cli/relaton_file.rb:142:in `concatenate_files'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-cli-1.7.0/lib/relaton/cli/relaton_file.rb:86:in `bibcollection'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-cli-1.7.0/lib/relaton/cli/relaton_file.rb:157:in `concatenate_and_write_to_files'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-cli-1.7.0/lib/relaton/cli/relaton_file.rb:19:in `concatenate'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-cli-1.7.0/lib/relaton/cli/relaton_file.rb:58:in `concatenate'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/site_generator.rb:62:in `build_collection_file'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/site_generator.rb:27:in `block in generate'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/site_generator.rb:26:in `chdir'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/site_generator.rb:26:in `generate'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/site_generator.rb:19:in `generate'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/commands/site.rb:23:in `generate'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli.rb:67:in `start'
	from /__enclose_io_memfs__/local/metanorma:190:in `<main>'
```

**Comment by andrew2net** [comment]
@CAMOBAP a source document is invalid. Elements `committee`, `workgroup`, and `commission` should have an `abbreviation`.
```
committee = element committee { IHO_Group }
workgroup = element workgroup { IHO_Group }
commission = element commission { IHO_Group }

IHO_Group =
  element name { text }?,
  element abbreviation { text },
  (committee | workgroup | commission)?
```
