### ISSUE TITLE
Compilation failure when IHO references are slightly misspelled

### ISSUE THREAD

**Issue by manuel489** [relaton/relaton-iho#7]
A compilation failure occur when an IHO reference is slightly misspelled.

For example:
*(Taken from [IHO s63](https://github.com/metanorma/mn-samples-iho/tree/master/sources/s63))*
````
[bibliography]
==== References

// Instead of writing "IHO S-63", it is written "IHO S63" for illustration of the issue

* [[[iho_s63_aa,IHO S63]]], IHO S-63 Data Protection Scheme, International Hydrographic Organisation

* [[[iho_s57_aa,IHO S57]]], IHO S-57 Transfer Standard for Digital Hydrographic Data, International Hydrographic Organisation
````

Part of error message:
````
[relaton-iho] ("IHO S63") fetching...
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/relaton-iho-1.2.2/lib/relaton_iho/iho_bibliography.rb:14:in `search': undefined local variable or method `returm' for RelatonIho::IhoBibliography:Class (NameError)
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/relaton-iho-1.2.2/lib/relaton_iho/iho_bibliography.rb:37:in `get'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/relaton-iho-1.2.2/lib/relaton_iho/processor.rb:19:in `get'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/relaton-1.2.0/lib/relaton/db.rb:180:in `new_bib_entry'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/relaton-1.2.0/lib/relaton/db.rb:167:in `check_bibliocache'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/relaton-1.2.0/lib/relaton/db.rb:31:in `fetch'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-standoc-1.4.2/lib/asciidoctor/standoc/ref_sect.rb:61:in `fetch_ref'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-standoc-1.4.2/lib/asciidoctor/standoc/ref.rb:196:in `refitem'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-standoc-1.4.2/lib/asciidoctor/standoc/ref.rb:240:in `reference1'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-standoc-1.4.2/lib/asciidoctor/standoc/ref.rb:249:in `block (2 levels) in reference'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-standoc-1.4.2/lib/asciidoctor/standoc/ref.rb:249:in `each'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-standoc-1.4.2/lib/asciidoctor/standoc/ref.rb:249:in `block in reference'
...
````

I understand that if a reference is not found via auto-fetch, user reference text should be used instead.

**Comment by andrew2net** [comment]
> I understand that if a reference is not found via auto-fetch, user reference text should be used instead.

@ronaldtse relaton-* gems don't get a reference text. The metanorma calls the get method with a reference only. But we can add a missing dash to reference. What do you think?

**Comment by ronaldtse** [comment]
@andrew2net this sounds like a Metanorma issue. Ping @opoudjis

**Comment by ronaldtse** [comment]
>  But we can add a missing dash to reference. What do you think?

@andrew2net yes, let's allow searching for without the dash too. Thanks.
